[model]
provider = "openrouter" #openrouter, gemini, ollama
model = "cohere/north-mini-code:free"
voice_actor = "id-ID-GadisNeural"

api_key = ""

[email]
email_host = ""
email_port = ""
email_user = ""
email_password = ""
